# Generated by Django 6.0.4 on 2026-04-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_section_studentmark_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='new_date',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='reschedule_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='reschedule_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='core.classschedule'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='new_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='monday', max_length=10),
            preserve_default=False,
        ),
    ]
